# 触发工作流的操作
on: push
# 工作流名字
name: Test, Build and Release apk
# 需要执行的任务
jobs:
  build:
    name: Build APK
    # 定义运行环境
    runs-on: ubuntu-latest
    # 执行步骤
    steps:
      # 步骤执行之前，先拉取最新代码
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      # 配置 Flutter 环境
      - uses: subosito/flutter-action@v1
        channel: "stable"
        with:
          flutter-version: '2.2.3'
      # 执行构建之前，更新 flutter 依赖
      - run: flutter pub get
      # 测试
      - run: flutter build apk --release
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN }}
          commit: main
          tag: v1.0.${{github.run_number}}
